# Default config for MagicArenas

# The base wand template to use for determining a player's current path
path_template: "wand"

# How often to check ("tick") active arenas, in ticks
tick_interval: 40